// <auto-generated />
using System;
using GameArchive.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameArchive.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260331205028_AddRegions")]
    partial class AddRegions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("GameArchive.Domain.Entities.ChecklistEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CollectionItemId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CollectionItemId");

                    b.ToTable("ChecklistEntries");
                });

            modelBuilder.Entity("GameArchive.Domain.Entities.ChecklistTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ChecklistTemplates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000001"),
                            ItemType = 1,
                            Label = "Box",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000002"),
                            ItemType = 1,
                            Label = "Controller",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000003"),
                            ItemType = 1,
                            Label = "Cables",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000005"),
                            ItemType = 0,
                            Label = "Box",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000006"),
                            ItemType = 0,
                            Label = "Manual",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("11111111-0000-0000-0000-000000000007"),
                            ItemType = 0,
                            Label = "Cartridge/Disc",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("GameArchive.Domain.Entities.CollectionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EstimatedValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PurchasePrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("GameArchive.Domain.Entities.Platform", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000001"),
                            Name = "NES",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000002"),
                            Name = "SNES",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000003"),
                            Name = "Nintendo 64",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000004"),
                            Name = "GameCube",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000005"),
                            Name = "Wii",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000006"),
                            Name = "Wii U",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000007"),
                            Name = "Nintendo Switch",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000008"),
                            Name = "Game Boy",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000009"),
                            Name = "Game Boy Color",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000010"),
                            Name = "Game Boy Advance",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000011"),
                            Name = "Nintendo DS",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000012"),
                            Name = "Nintendo 3DS",
                            SortOrder = 12
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000013"),
                            Name = "PlayStation",
                            SortOrder = 13
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000014"),
                            Name = "PlayStation 2",
                            SortOrder = 14
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000015"),
                            Name = "PlayStation 3",
                            SortOrder = 15
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000016"),
                            Name = "PlayStation 4",
                            SortOrder = 16
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000017"),
                            Name = "PlayStation 5",
                            SortOrder = 17
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000018"),
                            Name = "PSP",
                            SortOrder = 18
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000019"),
                            Name = "PS Vita",
                            SortOrder = 19
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000020"),
                            Name = "Xbox",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000021"),
                            Name = "Xbox 360",
                            SortOrder = 21
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000022"),
                            Name = "Xbox One",
                            SortOrder = 22
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000023"),
                            Name = "Xbox Series X/S",
                            SortOrder = 23
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000024"),
                            Name = "Sega Mega Drive",
                            SortOrder = 24
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000025"),
                            Name = "Sega Saturn",
                            SortOrder = 25
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000026"),
                            Name = "Sega Dreamcast",
                            SortOrder = 26
                        },
                        new
                        {
                            Id = new Guid("22222222-0000-0000-0000-000000000027"),
                            Name = "PC",
                            SortOrder = 27
                        });
                });

            modelBuilder.Entity("GameArchive.Domain.Entities.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000001"),
                            Name = "PAL",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000002"),
                            Name = "NTSC-U",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000003"),
                            Name = "NTSC-J",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000004"),
                            Name = "NTSC",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("33333333-0000-0000-0000-000000000005"),
                            Name = "Unknown",
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("GameArchive.Domain.Entities.ChecklistEntry", b =>
                {
                    b.HasOne("GameArchive.Domain.Entities.CollectionItem", "CollectionItem")
                        .WithMany("ChecklistEntries")
                        .HasForeignKey("CollectionItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CollectionItem");
                });

            modelBuilder.Entity("GameArchive.Domain.Entities.CollectionItem", b =>
                {
                    b.Navigation("ChecklistEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
